/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng ký tài khoản bệnh nhân
         * @description Tạo tài khoản mới và trả về hồ sơ, KHÔNG trả token.
         *
         *     Đăng ký xong client phải gọi tiếp `POST /auth/login` để đăng nhập. Tách hai bước để
         *     luồng đăng nhập chỉ có một đường đi duy nhất — cũng là chỗ sau này gắn xác thực email
         *     mà không phải đổi contract.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng nhập bằng email và mật khẩu
         * @description Trả cặp token kèm hồ sơ user, để client không phải gọi thêm `/auth/profiles`.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng nhập bằng Google OpenID Connect
         * @description Verify Google ID Token, tìm hoặc tạo user tương ứng, rồi trả cặp token hệ thống.
         *
         *     Cùng response contract với `/auth/login` — client không cần phân biệt hai luồng sau khi
         *     đăng nhập xong. Không tự động liên kết khi email trùng local account chưa link, xem
         *     `GoogleAccountConflictError` và ADR 0016.
         */
        post: operations["login_google_api_v1_auth_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Làm mới cặp token bằng refresh token
         * @description Chỉ nhận token loại `refresh`.
         *
         *     Access token gửi vào đây bị từ chối 401: refresh token sống 14 ngày còn access token
         *     sống 30 phút, chấp nhận nhầm loại là kéo dài vòng đời token bị lộ lên gấp hàng trăm
         *     lần. Kiểm tra nằm ở `domain.auth.decode_token(expected_type=...)`.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hồ sơ của user đang đăng nhập */
        get: operations["get_profile_api_v1_auth_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drugs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Drugs
         * @description Duyệt danh mục thuốc theo chữ cái, có phân trang.
         *
         *     Khác `/drugs/search`: endpoint này lọc TẤT ĐỊNH bằng chuỗi con, không chấm điểm khớp
         *     mờ — người dùng đang duyệt danh mục nên phải thấy đúng nội dung bảng `drugs`.
         */
        get: operations["list_drugs_api_v1_drugs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drugs/letters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Drug Letters
         * @description Đếm số thuốc theo từng chữ cái để dựng thanh A–Z.
         *
         *     ⚠️ Route tĩnh phải khai báo TRƯỚC `/{drug_id}` khi endpoint chi tiết được thêm vào,
         *     nếu không "letters" sẽ bị bắt như một drug_id và trả 404/422.
         */
        get: operations["list_drug_letters_api_v1_drugs_letters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drugs/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Drugs
         * @description Tra cứu danh mục thuốc qua `DrugRepository` và `domain/normalization.py`.
         *
         *     Ưu tiên khớp tên biệt dược: gõ một ký tự đã phải ra danh sách gợi ý, vì đây là ô
         *     autocomplete chứ không phải nút submit.
         */
        get: operations["search_drugs_api_v1_drugs_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diseases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Diseases */
        get: operations["search_diseases_api_v1_diseases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/me/health-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health Profile */
        get: operations["get_health_profile_api_v1_patients_me_health_profile_get"];
        /** Put Health Profile */
        put: operations["put_health_profile_api_v1_patients_me_health_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/me/conditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Condition */
        post: operations["add_condition_api_v1_patients_me_conditions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/me/conditions/{condition_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Condition */
        delete: operations["delete_condition_api_v1_patients_me_conditions__condition_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/me/diseases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Disease */
        post: operations["add_disease_api_v1_patients_me_diseases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/me/diseases/{patient_disease_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Disease */
        delete: operations["delete_disease_api_v1_patients_me_diseases__patient_disease_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interactions/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Interactions */
        post: operations["check_interactions_api_v1_interactions_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interaction-checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Checks */
        get: operations["list_checks_api_v1_interaction_checks_get"];
        put?: never;
        post?: never;
        /** Clear Checks */
        delete: operations["clear_checks_api_v1_interaction_checks_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interaction-checks/{check_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Check */
        get: operations["get_check_api_v1_interaction_checks__check_id__get"];
        put?: never;
        post?: never;
        /** Delete Check */
        delete: operations["delete_check_api_v1_interaction_checks__check_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prescriptions/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Prescription Images
         * @description Ảnh chỉ sống trong request; Gemini output vẫn phải được người dùng xác nhận với catalog.
         */
        post: operations["extract_prescription_images_api_v1_prescriptions_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_v1_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AISummary */
        AISummary: {
            /**
             * Status
             * @enum {string}
             */
            status: "generated" | "fallback";
            /** Warning */
            warning: string;
            /**
             * Managementbullets
             * @default []
             */
            managementBullets: string[];
        };
        /**
         * AuthUserResponse
         * @description Khớp `IAuthUser`. Tuyệt đối không thêm `password_hash` vào đây.
         */
        AuthUserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            /** Roles */
            roles: string[];
        };
        /** Body_extract_prescription_images_api_v1_prescriptions_extract_post */
        Body_extract_prescription_images_api_v1_prescriptions_extract_post: {
            /**
             * Images
             * @description 1–5 ảnh JPG, PNG hoặc WEBP của cùng một đơn thuốc
             */
            images: string[];
        };
        /** Citation */
        Citation: {
            /** Evidenceid */
            evidenceId: string;
            /** Chunkid */
            chunkId?: string | null;
            /** Quote */
            quote: string;
            /** Source */
            source: string;
            /** Sourceurl */
            sourceUrl: string;
            /** Page */
            page?: number | null;
            /** Section */
            section?: string | null;
        };
        /** DiseaseResponse */
        DiseaseResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** DiseaseSearchResponse */
        DiseaseSearchResponse: {
            /** Items */
            items: components["schemas"]["DiseaseResponse"][];
        };
        /** DiseaseSnapshot */
        DiseaseSnapshot: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * DrugCandidate
         * @description Một ứng viên thuốc trong kết quả tìm kiếm danh mục.
         */
        DrugCandidate: {
            /** Drugid */
            drugId: string;
            /** Brandname */
            brandName: string;
            /** Ingredient */
            ingredient: string;
            /** Confidence */
            confidence: number;
        };
        /**
         * DrugLetterCount
         * @description Số thuốc thuộc một nhóm chữ cái trên thanh A–Z.
         */
        DrugLetterCount: {
            /** Letter */
            letter: string;
            /** Count */
            count: number;
        };
        /**
         * DrugLetterIndexResponse
         * @description Chỉ mục chữ cái của danh mục (`GET /api/v1/drugs/letters`).
         *
         *     Luôn trả đủ 27 nhóm A–Z + `other`, kể cả nhóm có `count = 0`, để FE disable đúng nút
         *     thay vì dẫn người dùng tới một trang rỗng.
         */
        DrugLetterIndexResponse: {
            /** Letters */
            letters: components["schemas"]["DrugLetterCount"][];
            /** Total */
            total: number;
        };
        /**
         * DrugListItem
         * @description Một dòng trong danh mục thuốc (`GET /api/v1/drugs`).
         *
         *     Chỉ chứa dữ liệu định danh để render danh sách. Nội dung lâm sàng có trích dẫn nằm ở
         *     endpoint chi tiết — danh sách không hiển thị cảnh báo nên không đính kèm citation.
         */
        DrugListItem: {
            /** Id */
            id: string;
            /** Brandname */
            brandName: string;
            /** Ingredient */
            ingredient: string;
            /** Dosageform */
            dosageForm?: string | null;
            /** Route */
            route?: string | null;
            /** Hasleaflet */
            hasLeaflet: boolean;
        };
        /**
         * DrugListResponse
         * @description Một trang của danh mục thuốc (`GET /api/v1/drugs`).
         *
         *     Echo lại `letter`/`query` đã chuẩn hoá để FE đánh dấu đúng nút đang chọn trên thanh
         *     A–Z mà không phải tự suy lại từ URL.
         */
        DrugListResponse: {
            /** Items */
            items: components["schemas"]["DrugListItem"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
            /** Totalpages */
            totalPages: number;
            /** Letter */
            letter?: string | null;
            /** Query */
            query?: string | null;
        };
        /**
         * DrugSearchResponse
         * @description Kết quả tìm kiếm thuốc trong danh mục (`GET /api/v1/drugs/search`).
         */
        DrugSearchResponse: {
            /** Query */
            query: string;
            /** Candidates */
            candidates: components["schemas"]["DrugCandidate"][];
            /** Requiresconfirmation */
            requiresConfirmation: boolean;
        };
        /** DrugSnapshot */
        DrugSnapshot: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Brandname */
            brandName: string;
            /** Ingredient */
            ingredient: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ExtractedPrescriptionDisease */
        ExtractedPrescriptionDisease: {
            /** Rawtext */
            rawText: string;
            /** Name */
            name: string;
            /** Uncertain */
            uncertain: boolean;
            /** Candidates */
            candidates: components["schemas"]["PrescriptionDiseaseCandidate"][];
        };
        /** ExtractedPrescriptionDrug */
        ExtractedPrescriptionDrug: {
            /** Rawtext */
            rawText: string;
            /** Name */
            name: string;
            /** Ingredient */
            ingredient?: string | null;
            /** Uncertain */
            uncertain: boolean;
            /** Candidates */
            candidates: components["schemas"]["PrescriptionDrugCandidate"][];
        };
        /**
         * GoogleLoginRequest
         * @description Body của `POST /api/v1/auth/google` — xem ADR 0016.
         */
        GoogleLoginRequest: {
            /** Idtoken */
            idToken: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthProfileResponse */
        HealthProfileResponse: {
            /** Dateofbirth */
            dateOfBirth?: string | null;
            /** Sex */
            sex?: ("nu" | "nam" | "khac") | null;
            /** Weightkg */
            weightKg?: string | null;
            /** Heightcm */
            heightCm?: string | null;
            /** Consentedat */
            consentedAt?: string | null;
            /** Conditions */
            conditions?: components["schemas"]["PatientConditionResponse"][];
            /** Diseases */
            diseases?: components["schemas"]["PatientDiseaseResponse"][];
        };
        /** HealthProfileUpdate */
        HealthProfileUpdate: {
            /** Dateofbirth */
            dateOfBirth?: string | null;
            /** Sex */
            sex?: ("nu" | "nam" | "khac") | null;
            /** Weightkg */
            weightKg?: number | string | null;
            /** Heightcm */
            heightCm?: number | string | null;
            /** Consent */
            consent: boolean;
        };
        /** InteractionCheckListResponse */
        InteractionCheckListResponse: {
            /** Items */
            items: components["schemas"]["InteractionCheckSummary"][];
            /** Total */
            total: number;
        };
        /** InteractionCheckRequest */
        InteractionCheckRequest: {
            /** Drugids */
            drugIds: string[];
            /** Diseaseids */
            diseaseIds: string[];
        };
        /** InteractionCheckResponse */
        InteractionCheckResponse: {
            /** Checkid */
            checkId: string | null;
            /**
             * Historystatus
             * @enum {string}
             */
            historyStatus: "saved" | "not-saved";
            /**
             * Checkedat
             * Format: date-time
             */
            checkedAt: string;
            /** Drugs */
            drugs: components["schemas"]["DrugSnapshot"][];
            /** Diseases */
            diseases: components["schemas"]["DiseaseSnapshot"][];
            /** Severityscale */
            severityScale: components["schemas"]["SeverityScaleItem"][];
            /** Highlightid */
            highlightId: string | null;
            /** Items */
            items: components["schemas"]["InteractionItem"][];
            /** Notes */
            notes: components["schemas"]["InteractionNote"][];
            /** Unavailable */
            unavailable: components["schemas"]["UnavailableResult"][];
        };
        /** InteractionCheckSummary */
        InteractionCheckSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Drugnames */
            drugNames: string[];
            /** Diseasenames */
            diseaseNames: string[];
            /**
             * Checkedat
             * Format: date-time
             */
            checkedAt: string;
            /** Resultcount */
            resultCount: number;
            /** Notecount */
            noteCount: number;
            /** Unavailablecount */
            unavailableCount: number;
            /** Highestseverity */
            highestSeverity: ("contraindicated" | "major" | "moderate" | "minor" | "unknown") | null;
        };
        /** InteractionItem */
        InteractionItem: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "drug-drug" | "drug-disease" | "drug-food" | "drug-supplement";
            /**
             * Severity
             * @enum {string}
             */
            severity: "contraindicated" | "major" | "moderate" | "minor" | "unknown";
            /**
             * Reviewstatus
             * @enum {string}
             */
            reviewStatus: "pending" | "approved";
            /** Subject */
            subject: string;
            /** Object */
            object: string;
            /** Pairkey */
            pairKey?: string | null;
            /** Mechanism */
            mechanism?: string | null;
            /** Consequence */
            consequence?: string | null;
            /** Effectdescription */
            effectDescription?: string | null;
            /** Management */
            management?: string | null;
            aiSummary: components["schemas"]["AISummary"];
            /** Citations */
            citations: components["schemas"]["Citation"][];
        };
        /** InteractionNote */
        InteractionNote: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "drug-food" | "drug-supplement";
            /**
             * Severity
             * @enum {string}
             */
            severity: "contraindicated" | "major" | "moderate" | "minor" | "unknown";
            /**
             * Reviewstatus
             * @enum {string}
             */
            reviewStatus: "pending" | "approved";
            /** Subject */
            subject: string;
            /** Object */
            object: string;
            /** Pairkey */
            pairKey?: string | null;
            /** Mechanism */
            mechanism?: string | null;
            /** Consequence */
            consequence?: string | null;
            /** Effectdescription */
            effectDescription?: string | null;
            /** Management */
            management?: string | null;
            aiSummary: components["schemas"]["AISummary"];
            /** Citations */
            citations: components["schemas"]["Citation"][];
        };
        /**
         * LoginRequest
         * @description Khớp `ILoginRequest` — body của `POST /api/v1/auth/login`.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * LoginResponse
         * @description Khớp `ILoginResponse`.
         *
         *     Trả kèm `user` để client không phải gọi thêm `GET /auth/profiles` ngay sau khi đăng
         *     nhập. Endpoint refresh KHÔNG trả `user`: lúc đó client đã có hồ sơ rồi, và giữ hai
         *     response model tách bạch làm OpenAPI mô tả đúng từng luồng.
         */
        LoginResponse: {
            /** Accesstoken */
            accessToken: string;
            /** Refreshtoken */
            refreshToken: string;
            /** Expiresin */
            expiresIn: number;
            user: components["schemas"]["AuthUserResponse"];
        };
        /** PatientConditionCreate */
        PatientConditionCreate: {
            /**
             * Conditioncode
             * @enum {string}
             */
            conditionCode: "mang-thai" | "cho-con-bu";
        };
        /** PatientConditionResponse */
        PatientConditionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Conditioncode
             * @enum {string}
             */
            conditionCode: "mang-thai" | "cho-con-bu";
            /**
             * Source
             * @enum {string}
             */
            source: "self_reported" | "pharmacist_confirmed";
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** PatientDiseaseCreate */
        PatientDiseaseCreate: {
            /**
             * Diseaseid
             * Format: uuid
             */
            diseaseId: string;
        };
        /** PatientDiseaseResponse */
        PatientDiseaseResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Diseaseid
             * Format: uuid
             */
            diseaseId: string;
            /** Name */
            name: string;
            /**
             * Source
             * @enum {string}
             */
            source: "self_reported" | "pharmacist_confirmed";
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** PrescriptionDiseaseCandidate */
        PrescriptionDiseaseCandidate: {
            /**
             * Diseaseid
             * Format: uuid
             */
            diseaseId: string;
            /** Name */
            name: string;
            /** Confidence */
            confidence: number;
        };
        /** PrescriptionDrugCandidate */
        PrescriptionDrugCandidate: {
            /**
             * Drugid
             * Format: uuid
             */
            drugId: string;
            /** Brandname */
            brandName: string;
            /** Ingredient */
            ingredient: string;
            /** Confidence */
            confidence: number;
        };
        /** PrescriptionExtractionResponse */
        PrescriptionExtractionResponse: {
            /** Drugs */
            drugs: components["schemas"]["ExtractedPrescriptionDrug"][];
            /** Diseases */
            diseases: components["schemas"]["ExtractedPrescriptionDisease"][];
            /** Model */
            model: string;
            /**
             * Requiresconfirmation
             * @default true
             * @constant
             */
            requiresConfirmation: true;
        };
        /**
         * RefreshRequest
         * @description Khớp `IRefreshTokenRequest` — body của `POST /api/v1/auth/refresh`.
         */
        RefreshRequest: {
            /** Refreshtoken */
            refreshToken: string;
        };
        /**
         * RegisterRequest
         * @description Khớp `IRegisterRequest`.
         *
         *     KHÔNG có field `role`: đăng ký công khai luôn tạo PATIENT. Cho client tự chọn role
         *     đồng nghĩa với việc ai cũng tự cấp quyền dược sĩ và vào được `/review/**`.
         */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
        };
        /** SeverityScaleItem */
        SeverityScaleItem: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "contraindicated" | "major" | "moderate" | "minor" | "unknown";
            /** Label */
            label: string;
            /** Resultcount */
            resultCount: number;
        };
        /**
         * TokenPairResponse
         * @description Cặp token mới. Khớp `IRefreshTokenResponse`, thêm `expiresIn`.
         *
         *     `expires_in` là số giây còn lại của access token, để client tự lên lịch gọi refresh
         *     trước khi hết hạn thay vì phải đợi một request 401 rồi mới thử lại.
         */
        TokenPairResponse: {
            /** Accesstoken */
            accessToken: string;
            /** Refreshtoken */
            refreshToken: string;
            /** Expiresin */
            expiresIn: number;
        };
        /** UnavailableResult */
        UnavailableResult: {
            /** Key */
            key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "drug-drug" | "drug-disease";
            /** Subject */
            subject: string;
            /** Object */
            object: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "missing-record" | "missing-citation" | "source-unavailable";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserResponse"];
                };
            };
            /** @description Mật khẩu không đạt yêu cầu */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Email đã được đăng ký */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Sai email hoặc mật khẩu */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Tài khoản bị vô hiệu hoá */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_google_api_v1_auth_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Google ID token không hợp lệ, hết hạn, hoặc email chưa xác thực */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Email đã có tài khoản nhưng chưa liên kết Google */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description Refresh token hỏng hoặc hết hạn */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Tài khoản bị vô hiệu hoá */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_v1_auth_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_drugs_api_v1_drugs_get: {
        parameters: {
            query?: {
                /** @description Lọc theo chữ cái đầu của tên biệt dược: "A"–"Z", hoặc "other" cho tên không bắt đầu bằng chữ cái */
                letter?: string | null;
                /** @description Lọc chuỗi con trên tên biệt dược hoặc hoạt chất */
                q?: string | null;
                /** @description Số trang, bắt đầu từ 1 */
                page?: number;
                /** @description Số dòng mỗi trang */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrugListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_drug_letters_api_v1_drugs_letters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrugLetterIndexResponse"];
                };
            };
        };
    };
    search_drugs_api_v1_drugs_search_get: {
        parameters: {
            query: {
                /** @description Từ khoá tên biệt dược hoặc hoạt chất */
                q: string;
                /** @description Số lượng ứng viên tối đa trả về */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrugSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_diseases_api_v1_diseases_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiseaseSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_profile_api_v1_patients_me_health_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthProfileResponse"];
                };
            };
        };
    };
    put_health_profile_api_v1_patients_me_health_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HealthProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_condition_api_v1_patients_me_conditions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientConditionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientConditionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_condition_api_v1_patients_me_conditions__condition_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                condition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_disease_api_v1_patients_me_diseases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientDiseaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientDiseaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_disease_api_v1_patients_me_diseases__patient_disease_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_disease_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_interactions_api_v1_interactions_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InteractionCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InteractionCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_checks_api_v1_interaction_checks_get: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InteractionCheckListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_checks_api_v1_interaction_checks_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_check_api_v1_interaction_checks__check_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                check_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InteractionCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_check_api_v1_interaction_checks__check_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                check_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_prescription_images_api_v1_prescriptions_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_prescription_images_api_v1_prescriptions_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrescriptionExtractionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_v1_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
