"""Batch Proofreader CLI script.

Proofreads all Markdown (.md) files generated by Qwen OCR using Gemini Line-Diff Proofreader.
Supports resuming, multithreading, and custom input/output directories.

Usage:
    python scripts/batch_proofread.py --dir output/
    python scripts/batch_proofread.py --dir output/ --workers 5
"""

import argparse
import logging
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

# Add backend/src to sys.path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "backend" / "src"))

from medsafe.ocr.line_proofreader import LineDiffProofreader
from tqdm import tqdm

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)


import json
import random
import time


def process_single_file(
    md_path: Path,
    proofreader: LineDiffProofreader,
    out_dir: Path,
    diff_dir: Path | None = None,
    skip_existing: bool = True,
    delay: float = 0.0,
) -> tuple[str, bool, str]:
    out_path = out_dir / md_path.name

    if skip_existing and out_path.exists() and out_path.stat().st_size > 0:
        return (md_path.name, True, "Skipped (already exists)")

    try:
        raw_content = md_path.read_text(encoding="utf-8")
        if not raw_content.strip():
            out_dir.mkdir(parents=True, exist_ok=True)
            out_path.write_text("", encoding="utf-8")
            return (md_path.name, True, "Empty file skipped")

        proofread_content, diffs = proofreader.proofread_markdown_with_diff(raw_content)

        if delay > 0:
            jitter = random.uniform(0.5, 2.0)
            actual_delay = delay + jitter
            time.sleep(actual_delay)

        out_dir.mkdir(parents=True, exist_ok=True)
        out_path.write_text(proofread_content, encoding="utf-8")

        if diff_dir is not None:
            diff_dir.mkdir(parents=True, exist_ok=True)
            diff_file = diff_dir / f"{md_path.stem}.diff.json"
            diff_file.write_text(json.dumps(diffs, ensure_ascii=False, indent=2), encoding="utf-8")

        return (md_path.name, True, f"Saved ({len(diffs)} diffs)")

    except Exception as e:
        logger.error(f"Failed to proofread {md_path.name}: {e}")
        return (md_path.name, False, str(e))


def main():
    parser = argparse.ArgumentParser(
        description="Batch proofread Markdown OCR files using Gemini Line-Diff Proofreader."
    )
    parser.add_argument(
        "--dir",
        type=str,
        default="output_clean_v3",
        help="Directory containing Markdown files to proofread (default: output_clean_v3).",
    )
    parser.add_argument(
        "--out-dir",
        type=str,
        default="output_clean_v3_proofread_noImg",
        help="Custom output directory for proofread Markdown files (default: output_clean_v3_proofread_noImg).",
    )
    parser.add_argument(
        "--diff-dir",
        type=str,
        default="output_clean_v3_diffs_noImg",
        help="Custom output directory for diff JSON audit files (default: output_clean_v3_diffs_noImg).",
    )
    parser.add_argument(
        "--api-key",
        type=str,
        default=None,
        help="Google Gemini API Key override.",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=2,
        help="Number of concurrent worker threads (default: 2 to respect 15 RPM Free Tier).",
    )
    parser.add_argument(
        "--model",
        type=str,
        default="gemini-3.5-flash-lite",
        help="Gemini model name override (default: gemini-3.5-flash-lite).",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Maximum number of files to process.",
    )
    parser.add_argument(
        "--delay",
        type=float,
        default=4.5,
        help="Delay in seconds between requests per worker to respect Rate Limits (default: 4.5s for Free Tier 15 RPM).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Force re-proofreading even if output file already exists.",
    )

    args = parser.parse_args()

    in_dir = Path(args.dir)
    if not in_dir.exists() or not in_dir.is_dir():
        logger.error(f"Input directory does not exist: {in_dir}")
        sys.exit(1)

    out_dir = Path(args.out_dir) if args.out_dir else in_dir
    diff_dir = Path(args.diff_dir) if args.diff_dir else None
    md_files = [
        f for f in sorted(in_dir.glob("*.md"))
        if not f.name.startswith("sample_") and not f.name.endswith("_proofread_test.md")
    ]

    if args.limit:
        md_files = md_files[: args.limit]

    if not md_files:
        logger.warning(f"No Markdown (.md) files found in {in_dir}")
        sys.exit(0)

    logger.info(f"Found {len(md_files)} Markdown file(s) to process in {in_dir}")
    logger.info(f"Using Gemini Line-Diff Proofreader ({args.model or 'default'}) with {args.workers} worker threads (delay: {args.delay}s)...")

    proofreader = LineDiffProofreader(api_key=args.api_key, model=args.model)
    skip_existing = not args.force
    success_count = 0

    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        futures = {
            executor.submit(
                process_single_file, md_file, proofreader, out_dir, diff_dir, skip_existing, args.delay
            ): md_file
            for md_file in md_files
        }

        for future in tqdm(
            as_completed(futures), total=len(md_files), desc="Batch Proofread", unit="file"
        ):
            name, ok, msg = future.result()
            if ok:
                success_count += 1

    print("\nBatch Proofreading Complete!")
    print(f"Total Files: {len(md_files)}")
    print(f"Successful: {success_count}")
    print(f"Output Directory: {out_dir.resolve()}")


if __name__ == "__main__":
    main()
